### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 3)

### ISSUE THREAD

**Issue by kaustesseract** [alvinliu0/HA2G#20]
Hello, 

I am trying to run the train_expressive.py (HA2G model) file for the TED Expressive Dataset. However, I am encountering the following error.

Traceback (most recent call last):
  File "scripts/train_expressive.py", line 900, in <module>
    main({'args': _args})
  File "scripts/train_expressive.py", line 895, in main
    pose_dim=pose_dim, speaker_model=train_dataset.speaker_model)
  File "scripts/train_expressive.py", line 237, in train_epochs
    val_metrics = evaluate_testset(test_data_loader, generator, g1, g2, g3, g4, g5, g6, audio_encoder, loss_fn, embed_space_evaluator, args)
  File "scripts/train_expressive.py", line 418, in evaluate_testset
    for iter_idx, data in enumerate(test_data_loader, 0):
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/me12/kaustubk/miniconda/envs/HAG/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/fs03/me12/HA2G/scripts/data_loader/lmdb_data_loader_expressive.py", line 119, in __getitem__
    word_seq, pose_seq, vec_seq, audio, spectrogram, aux_info = sample
ValueError: not enough values to unpack (expected 6, got 3)

I am using the downloadable TED Expressive dataset from the given link in the repo.

Also, the error is happening after calling the pyarrow.deserialize function in the __getitem__ function of the lmdb_ data_loader_expressive.py file. 
Anyone's help would be highly appreciable.

**Comment by ZZQ00100** [comment]
Have you solved this problem? I also encountered a similar problem
word_seq, pose_seq, vec_seq, audio, spectrogram, aux_info = sample
ValueError: not enough values to unpack (expected 6, got 5)
